
# FROM postgres:15-alpine

# this image is itnegrated with PGvector -- https://github.com/pgvector/pgvector#additional-installation-methods
FROM ankane/pgvector

EXPOSE 5432

RUN mkdir /app && \
    mkdir /app/datamodel && \
    mkdir /app/samples

COPY ./setup/setup_datamodel.sql /app/datamodel/setup_datamodel.sql
COPY ./setup/setup_libraries.sql /app/datamodel/setup_libraries.sql
COPY ./samples/* /app/samples

ENV APP_SETUP_PATH=/app/datamodel
ENV APP_SETUP_FILE=/app/datamodel/setup_datamodel.sql
ENV APP_LIB_SETUP_FILE=/app/datamodel/setup_libraries.sql
ENV APP_SAMPLES_PATH=/app/samples
ENV APP_TESTING_MODE=false

COPY ./setup/setup.sh /docker-entrypoint-initdb.d/setup.sh