
FROM python:3.9.17-slim

RUN apt update && \
    apt upgrade -y

RUN mkdir /app && \
    mkdir /app/requirements 

COPY ./requirements.txt /app/requirements/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements/requirements.txt && \
    rm -rf /app/requirements

RUN mkdir /app/src
COPY ./src /app/src/

EXPOSE 5000

WORKDIR /app/src
CMD uvicorn main:api --host 0.0.0.0 --port 5000 ${UVICORN_OPTIONS}