
FROM python:3.9.17-slim

RUN apt update && \
    apt upgrade -y

RUN mkdir /app && \
    mkdir /app/requirements && \
    mkdir /app/src && \
    mkdir /app/logs && \
    mkdir /app/logs/main_app

COPY ./requirements.txt /app/requirements/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements/requirements.txt && \
    rm -rf /app/requirements

COPY . /app/src
RUN pip install -e /app/src

EXPOSE 5000

WORKDIR /app/src/main_app

ENV UVICORN_WEB_CONCURRENCY=10
ENV UVICORN_CMD_OPTIONS= 
ENV APP_DEBUG_MODE=false
ENV APP_LOG_PATH=/app/logs/main_app
ENV APP_LOG_NAME=main_app
ENV APP_LOG_LAYER=9999

CMD uvicorn main_app.main:api --host 0.0.0.0 --port 5000 ${UVICORN_CMD_OPTIONS}