import os
import sys
import json
from fastapi import status
from testing_hl2_framework import *

interactive = True
test_no_idx = -1
test_steps = []

def wait(msg:str, default_return:str = "", close_command = ":c") -> str:
    if interactive:
        msg_wait = msg + (f"(enter '{close_command}' to close)" if close_command is not None else "")
        res = input(msg_wait) or default_return
        if close_command is not None and res == close_command:
            test_end(True, "Test closed by user")
        else:
            return res
    else:
        return default_return

def test_header():
    global test_idx, test_title, test_description, test_expected_results
    print("===================== * ========================")
    print(f"TEST NUMBER {test_idx} : '{test_title}'\n")
    print(f"->\tDescription:{test_description}\n")
    print(f"->\tExpeced Results:{test_expected_results}\n")
    print("===================== * ========================")

def test_step(msg:str, expected:str = ""):
    global test_no_idx, test_steps
    test_no_idx = test_no_idx + 1
    msg_step = f"[{test_no_idx+1}]\t" + msg + ( ("\n\t\t" + expected) if expected != "" else "" )
    test_steps.append(msg_step)
    print(f"===================== [{test_no_idx+1}] ========================")
    print(msg_step)

def test_step_add_data(msg:str):
    global test_no_idx, test_steps
    test_steps[test_no_idx] += f"\n\t\tRESULTS:\n\t\t{msg}"

def test_end(success:bool, msg:str):
    global test_idx, test_steps
    print("===================== * ========================")
    print(f"TEST NUMBER {test_idx} {'SUCCESS' if success else 'FAILED'}")
    print("->\t" + msg)
    print("Steps performed:\n" + ( "\n".join(test_steps) if len(test_steps) > 0 else "\t...empty"))
    print("===================== * ========================")
    sys.exit(0 if success else 1)




# test header

test_idx = 2
test_title = "Collaborative exploration"

test_description = """
This is a small example of collaborative exploration between two users. 
1. USER1 login (father session), USER2 login (as child session of USER1)
2. USER2 (child session) generates 2 new positions
3. USER1 generates another two other positions unknown to USER2
4. (collaboration) USER1 asks for a download, and receives the positions generated by USER2
5. USER2 logout and login
6. USER2 download: it receives the entire set of positions
7. USER1 logout, USER2 logout
"""

test_expected_results = """
Steps performed:
[1]     USER1 login
[2]     USER1 first download request
                no new positions; max_idx=0
                RESULTS:
                (True, '3b4d6f49a225b170fcfb66d003667074', 0, [], [])
[3]     USER2 login
[4]     USER2 first download request
                no new positions; max_idx=0; (not visible by request) it is a child session of USER1
                RESULTS:
                (True, '0a2a067ce1ed683016f29a0d2da290fd', 0, [], [])
[5]     USER2 upload
                no renamings from server
                RESULTS:
                (True, 2, [])
                RESULTS:
                wp_alignment: 0
[6]     USER1 upload
                renamings expected: 1->3, 2->4 (with max_idx=4)
                RESULTS:
                (True, 4, [{'request_position_id': 2, 'aligned_position_id': 4}, {'request_position_id': 1, 'aligned_position_id': 3}])
                RESULTS:
                wp_alignment: 2
[7]     USER1 download request (collaboration)
                USER1 receives the positions 1,2 generated by USER2
                RESULTS:
                (True, None, 4, [{'pos_id': 2, 'area_id': 0, 'v': [0.0, 0.0, 4.0], 'wp_timestamp': '2023-08-29T13:21:20'}, {'pos_id': 1, 'area_id': 0, 'v': [0.0, 0.0, 2.0], 'wp_timestamp': '2023-08-29T13:20:57'}], [{'wp1': 1, 'wp2': 0, 'dist': 2.0, 'pt_timestamp': '2023-08-29T13:20:57'}, {'wp1': 2, 'wp2': 1, 'dist': 2.0, 'pt_timestamp': '2023-08-29T13:21:20'}])
[8]     USER2 logout
[9]     USER2 login
[10]    USER2 first download request (again)
                max_idx=4, the device receives all the positions around the center
                RESULTS:
                (True, 'bbf8474436682d6a1f0b1869fa85f2fd', 4, [{'pos_id': 2, 'area_id': 0, 'v': [0.0, 0.0, 4.0], 'wp_timestamp': '2023-08-29T13:21:20'}, {'pos_id': 1, 'area_id': 0, 'v': [0.0, 0.0, 2.0], 'wp_timestamp': '2023-08-29T13:20:57'}, {'pos_id': 3, 'area_id': 0, 'v': [2.0, 0.0, 0.0], 'wp_timestamp': '2023-08-29T13:20:57'}, {'pos_id': 4, 'area_id': 0, 'v': [4.0, 0.0, 0.0], 'wp_timestamp': '2023-08-29T13:21:20'}], [{'wp1': 1, 'wp2': 0, 'dist': 2.0, 'pt_timestamp': '2023-08-29T13:20:57'}, {'wp1': 2, 'wp2': 1, 'dist': 2.0, 'pt_timestamp': '2023-08-29T13:21:20'}, {'wp1': 3, 'wp2': 0, 'dist': 2.0, 'pt_timestamp': '2023-08-29T13:20:57'}, {'wp1': 4, 'wp2': 3, 'dist': 2.0, 'pt_timestamp': '2023-08-29T13:21:20'}])
[11]    USER2 logout
[12]    USER1 logout
"""

test_header()



# test data

user1_data = {
    "user_id" : "SARHL2_ID8849249249_USER",
    "approver_id" : "SARHL2_ID8849249249_USER",
    "access_key" : "anoth3rBr3akabl3P0sswArd",
    "device_id" : "SARHL2_ID8651165355_DEVC",
    "ref_id" : "SARHL2_ID1234567890_REFP",
    "session_token" : None,
    "based_on" : ""
}
print(f"user1 DATA:\n{dict2json(user1_data)}")
user2_data = {
    "user_id" : "SARHL2_ID2894646521_USER",
    "approver_id" : "SARHL2_ID2894646521_USER",
    "access_key" : "s3vHngLh_F3s",
    "device_id" : "SARHL2_ID7864861468_DEVC",
    "ref_id" : "SARHL2_ID1234567890_REFP",
    "session_token" : None,
    "based_on" : ""
}
print(f"user2 DATA:\n{dict2json(user2_data)}")

wait("press a key to start the test ... ")
# ...



# test execution

test_step(
    msg = "USER1 login",
    expected = "")
wait("Press a key to start the test ... ")
success, session_token = api_access(
    user1_data['user_id'],
    user1_data["approver_id"],
    user1_data["access_key"],
    user1_data['device_id']
)
if not success:
    test_end(False, "login failed USER1")
else:
    user1_data['session_token'] = session_token
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER1 first download request",
    expected = "no new positions; max_idx=0")
wait("Press a key to start the test ... ")
success, based_on, max_idx, waypoints, paths = api_download(
    user1_data["user_id"],
    user1_data["device_id"],
    user1_data['ref_id'],
    user1_data['session_token'],
    "",
    [0.0, 0.0, 0.0],
    4.5
)
test_step_add_data(f"{(success, based_on, max_idx, waypoints, paths)}")
if not success:
    test_end(False, "USER1: cannot perform first download!")
elif based_on == "":
    test_end(False, "USER1: fake token is empty!")
else:
    user1_data["based_on"] = based_on
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 login",
    expected = "")
wait("Press a key to start the test ... ")
success, session_token = api_access(
    user2_data['user_id'],
    user2_data["approver_id"],
    user2_data["access_key"],
    user2_data['device_id']
)
if not success:
    test_end(False, "login failed USER2")
else:
    user2_data['session_token'] = session_token
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 first download request",
    expected = "no new positions; max_idx=0; (not visible by request) it is a child session of USER1")
wait("Press a key to start the test ... ")
success, based_on, max_idx, waypoints, paths = api_download(
    user2_data["user_id"],
    user2_data["device_id"],
    user2_data['ref_id'],
    user2_data['session_token'],
    "",
    [0.0, 0.0, 0.0],
    4.5
)
test_step_add_data(f"{(success, based_on, max_idx, waypoints, paths)}")
if not success:
    test_end(False, "USER2: cannot perform first download!")
elif based_on == "":
    test_end(False, "USER2: fake token is empty!")
else:
    user2_data["based_on"] = based_on
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 upload",
    expected = "no renamings from server")
wait("Press a key to start the test ... ")
success, max_id, wp_alignment = api_upload(
    user2_data['user_id'],
    user2_data['device_id'],
    user2_data['ref_id'],
    user2_data['session_token'],
    user2_data['based_on'],
    [
        {"pos_id":1,"area_id":0,"v":[0,0,2],"wp_timestamp":"2023/08/29 13:20:57"},
        {"pos_id":2,"area_id":0,"v":[0,0,4],"wp_timestamp":"2023/08/29 13:21:20"}
    ],
    [
		{"wp1":1,"wp2":0,"dist":2,"pt_timestamp":"2023/08/29 13:21:20"},
		{"wp1":2,"wp2":1,"dist":2,"pt_timestamp":"2023/08/29 13:21:20"}
    ]
)
test_step_add_data(f"{(success, max_id, wp_alignment)}")
if not success:
    test_end(False, "USER2: cannot upload data")
else:
    test_step_add_data(f"wp_alignment: {len(wp_alignment)}")
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER1 upload",
    expected = "renamings expected: 1->3, 2->4 (with max_idx=4)")
wait("Press a key to start the test ... ")
success, max_id, wp_alignment = api_upload(
    user1_data['user_id'],
    user1_data['device_id'],
    user1_data['ref_id'],
    user1_data['session_token'],
    user1_data['based_on'],
    [
        {"pos_id":1,"area_id":0,"v":[2,0,0],"wp_timestamp":"2023/08/29 13:20:57"},
        {"pos_id":2,"area_id":0,"v":[4,0,0],"wp_timestamp":"2023/08/29 13:21:20"}
    ],
    [
		{"wp1":1,"wp2":0,"dist":2,"pt_timestamp":"2023/08/29 13:21:20"},
		{"wp1":2,"wp2":1,"dist":2,"pt_timestamp":"2023/08/29 13:21:20"}
    ]
)
test_step_add_data(f"{(success, max_id, wp_alignment)}")
if not success:
    test_end(False, "USER2: cannot upload data")
else:
    test_step_add_data(f"wp_alignment: {len(wp_alignment)}")
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER1 download request (collaboration)",
    expected = "USER1 receives the positions 1,2 generated by USER2")
wait("Press a key to start the test ... ")
success, based_on, max_idx, waypoints, paths = api_download(
    user1_data["user_id"],
    user1_data["device_id"],
    user1_data['ref_id'],
    user1_data['session_token'],
    user1_data["based_on"],
    [0.0, 0.0, 0.0],
    4.5
)
test_step_add_data(f"{(success, based_on, max_idx, waypoints, paths)}")
if not success:
    test_end(False, "USER1: cannot perform download!")
else:
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 logout",
    expected = "")
wait("Press a key to start the test ... ")
success = api_release(
    user2_data['user_id'],
    user2_data['session_token']
)
if not success:
    test_end(False, "USER2: cannot release session")
else:
    user2_data['session_token'] = None
    user2_data['based_on'] = ""
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 login",
    expected = "")
wait("Press a key to start the test ... ")
success, session_token = api_access(
    user2_data['user_id'],
    user2_data["approver_id"],
    user2_data["access_key"],
    user2_data['device_id']
)
if not success:
    test_end(False, "USER2: login failed")
else:
    user2_data['session_token'] = session_token
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 first download request (again)",
    expected = "max_idx=4, the device receives all the positions around the center")
wait("Press a key to start the test ... ")
success, based_on, max_idx, waypoints, paths = api_download(
    user2_data["user_id"],
    user2_data["device_id"],
    user2_data['ref_id'],
    user2_data['session_token'],
    "",
    [0.0, 0.0, 0.0],
    4.5
)
test_step_add_data(f"{(success, based_on, max_idx, waypoints, paths)}")
if not success:
    test_end(False, "USER2: cannot perform first download!")
elif based_on == "":
    test_end(False, "USER2: fake token is empty!")
else:
    user2_data["based_on"] = based_on
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER2 logout",
    expected = "")
wait("Press a key to start the test ... ")
success = api_release(
    user2_data['user_id'],
    user2_data['session_token']
)
if not success:
    test_end(False, "USER2: cannot release session")
else:
    user2_data['session_token'] = None
    user2_data['based_on'] = ""
    wait("OK! Next ...")

# ...

test_step(
    msg = "USER1 logout",
    expected = "")
wait("Press a key to start the test ... ")
success = api_release(
    user1_data['user_id'],
    user1_data['session_token']
)
if not success:
    test_end(False, "USER2: cannot release session")
else:
    user1_data['session_token'] = None
    user1_data['based_on'] = ""
    wait("OK! end of the test session ...")

# ...



# end of test
test_end(True, "Test succeeded. Closing...")